### ISSUE TITLE
Cannot connect to the Magstim rapid2 via User Interface

### ISSUE THREAD

**Issue by Lena-Marreel** [nigelrogasch/MAGIC#14]
Dear anyone who can help, 

We are experiencing issues connecting to our recently acquired a Magstim Super Rapid system. Specifically if we want to use the User Interface.

In the past we have successfully used the MAGIC toolbox with out 200² Magstim system. Using the new configuration for our TTL cable.
magstimObj=magstim( 'COM4' );
magstimObj.connect();

With our new Rapid system the set up has remained the same, we have the unlock code and adjusted the code to the new system. 
magstimObj=rapid( 'COM4', 'Super',unlockCode);
magstimObj.connect(); 

It is our understanding the TTL cable should be connected to the Isolated Trigger port, at the back of the User Interface. With this cable configuration we get the following error.
Warning: Unsuccessful read: The specified amount of data was not returned within the Timeout period. 'serial' unable to read any data. 
ans = 0;

However, when we connect the TTL cable directly to the Rapid² mainframe (where normally you connect the User Interface to the mainframe) we can connect just fine and fire charges from our coil. Leading us to believe our TTL cable configuration and unlockCode are correct. Unfortunately, with this alternative cable configuration we disconnect and thus lose access to the User Interface and all its features. 

I would be very grateful for any feedback, input and suggestions on the appropriate set up (e.g., where should the TTL cable go?), if anyone had any similar issues and how you made it work for you.

Many thanks,
Lena Marreel

**Comment by umair-hassan** [comment]
Dear Lena,

Thank you for your message. Can you make sure if the BNC cable is working proplery? May be test with some other device?

This will be the first troubleshooting step. 

Thank you,
Umair

**Comment by Lena-Marreel** [comment]
> Dear Lena,
> 
> Thank you for your message. Can you make sure if the BNC cable is working proplery? May be test with some other device?
> 
> This will be the first troubleshooting step.
> 
> Thank you, Umair

Dear Umair,

Thank you for your response and suggestion! 
I believe the BNC cable you mention is the cable we refer to as the ''TTL cable''. I can confirm this cable is working. Both when used to connect with our 200² Magstim system, as well as the Rapid system (as long as plugged directly into the mainframe). 

Thank you,
Lena

**Comment by Lena-Marreel** [comment]
* sorry, accidental click of wrong button*

**Comment by longevity-software** [comment]
Hi Lena,

You cannot externally control the system with the user interface connected, the mainframe can only connect to one host controller and that will be the UI when it is connected.

Hope that helps. 
Graham

**Comment by Lena-Marreel** [comment]
> Hi Lena,
> 
> You cannot externally control the system with the user interface connected, the mainframe can only connect to one host controller and that will be the UI when it is connected.
> 
> Hope that helps. Graham

Hi Graham,

Thank you very much for this. You saved us time looking for a solution that does not exist. 

Lena
