### ISSUE TITLE
Unable to connect MagVenture MagPro X100

### ISSUE THREAD

**Issue by TingniLi** [nigelrogasch/MAGIC#24]
Hello,

I am trying to use Magic to control a MagPro X100 on Win11 with matlab 2022b, the TMS port is 'COM1', using a USB to serial port cable (standard Null-Modem cables (RS232) in which the pins 2 and 3 are crossed) and its baudrate can be set to 38400.

But I'm having the following error:

At the beginning, it only showed warnings, but the connect function returns false:
![image](https://github.com/nigelrogasch/MAGIC/assets/38412899/ea805b61-31de-4271-a231-c35f3ce00ba4)

When I try the connect function again, it showed errors like this:
![error2](https://github.com/nigelrogasch/MAGIC/assets/38412899/d5255e7a-8cf7-4113-bac1-173a5ddb958f)

and then, now when I try to define the magventure again, it also fails:
![image](https://github.com/nigelrogasch/MAGIC/assets/38412899/d4c2730f-977f-498c-b227-528bf0b90053)

I've also tried restarting all my equipment (both TMS and computer) and reconnecting the cables, but nothing works.

Much appreciated if you have a solution or any suggestions for this case.

Thank you so much for developing this toolbox!

Best,
Tingni

**Comment by umair-hassan** [comment]
Hi Tingni,

Connection function returning false is something we need to fix but can you confirm if the device was really not connected at all?

You will need to used myMV.disconnect() before connecting it again, or use the command: delete(allinstrfind) to clear the workspace.
