### ISSUE TITLE
Dimensions of arrays being concatenated are not consistent.

### ISSUE THREAD

**Issue by MarMykland** [nigelrogasch/MAGIC#6]
Hi, when trying to control magventure magpro I get this error seting up IPI or MODE i.e. Do you have any suggestions for a fix?

> Error using vertcat
> Dimensions of arrays being concatenated are not consistent.
> 
> Error in magventure/setIPI (line 1386)
>                commandBytes = [commandID;setVal;model;mode;currentDir;waveform;burstPulseIndex;ipi_M;ipi_L;...
> 
> Error in MF5ppTMStest (line 29)
> myMV.setIPI(2,'Normal',2,1.5,0);

`myMV.setIPI(2,'Normal',2,1.5,0);`

**Comment by MarMykland** [comment]
If I use this code I get this error:

> Index exceeds the number of array elements (0).
> 
> Error in magventure/setMode (line 725)
>                 getResponse = varargin{1};

`myMV.setMode('Twin','Normal',2,8,1);`

But it seems to work if I set the version back to before the edits 3rd of April. Is it siply that the check for input validity is faulty?

**Comment by MarMykland** [comment]
It seems to work by adjusting to the before april 3th version, but no matter how I tweak I get everything to work exept changing mode. Even if I use the before april 3th version I get it to work if I manually set it to twin mode, but if it is in standard mode I get this error for setIPI even though setIPI work if I am in twin mode manually.


> Dot indexing is not supported for variables of this type.
> 
> Error in magventure/setIPI (line 1251)
>                model = rawInfo.Model; %5th Byte of getInfo response
> 
> Error in MF5ppTMS (line 30)
> myMV.setIPI(10);

`myMV.setMode('Twin');
myMV.setIPI(10);
myMV.setBARatio(1.5);`
```

**Comment by bzf567** [comment]
Hope you have fixed it. 
The problem is with 'Normal'. I think the current codes are missing
> `            switch currentDirection
                case 'Normal'
                    currentDirN = '00';
                case 'Reverse'
                    currentDirN = '01';
            end`
`            currentDir = currentDirN;`

**Comment by bzf567** [comment]
Or, 
When you us these funcitons, inputing '00' insteatd of 'Normal', '01' insteatd of 'Reverse'
